Add the jessie-newton-backports repo to sbuild
1/ Add the jessie-newton-backports to the sbuild chroot
2/ Use NODEPOOL_MIRROR_HOST instead of hardcoded rax.
3/ Make a fake mirror from jessie-newton-backports, not jessie-newton
4/ Attempt to build a backport for sphinx

Change-Id: I4f3624d2f83332878fe767b61c90b5788aa60f74

diff --git a/check-and-build-bpo b/check-and-build-bpo
--- a/check-and-build-bpo
+++ b/check-and-build-bpo
@@ -9,6 +9,15 @@ else
    . /etc/pkgos/pkgos.conf
 fi
 
+if ! [ -r /etc/nodepool/provider ] ; then
+    echo "Could not read /etc/nodepool/provider"
+    exit 1
+else
+    . /etc/nodepool/provider
+    NODEPOOL_MIRROR_HOST=${NODEPOOL_MIRROR_HOST:-mirror.$NODEPOOL_REGION.$NODEPOOL_CLOUD.openstack.org}
+    NODEPOOL_MIRROR_HOST=$(echo $NODEPOOL_MIRROR_HOST|tr '[:upper:]' '[:lower:]')
+fi
+
 HERE=$(pwd)
 LAST_GIT_COMMIT=$(git log | head -n 1 | awk '{print $2}')
 
@@ -16,6 +25,14 @@ cleanup_data () {
     rm -rf ${HERE}/etc
     rm -f ${HERE}/rebuild-list-sid ${HERE}/rebuild-list-experimental
     rm -rf bpo-src uploads
+}
+
+add_bpo_repo_to_sbuild () {
+    echo "deb http://${NODEPOOL_MIRROR_HOST}/debian-openstack jessie-newton-backports main
+deb-src http://${NODEPOOL_MIRROR_HOST}/debian-openstack jessie-newton-backports main
+" >/tmp/jessie-newton-backports.list
+    sudo cp /tmp/jessie-newton-backports.list /var/lib/sbuild/jessie-newton/etc/apt/sources.list.d/jessie-newton-backports.list
+    sudo sbuild-update -udcar jessie-newton-amd64-sbuild
 }
 
 make_ssh_keys () {
@@ -95,10 +112,11 @@ rebuild_all_bpo () {
 
 
 cleanup_data
+add_bpo_repo_to_sbuild
 make_ssh_keys
-make_fake_mirror jessie-newton http://mirror.dfw.rax.openstack.org/debian-openstack
+make_fake_mirror jessie-newton-backports http://${NODEPOOL_MIRROR_HOST}/debian-openstack
 for DEBIAN_SUITE_TO_BUILD in sid ; do
-    make_fake_mirror $DEBIAN_SUITE_TO_BUILD ${CLOSEST_DEBIAN_MIRROR}
+    make_fake_mirror $DEBIAN_SUITE_TO_BUILD http://httpredir.debian.org/debian
     decide_to_build_or_not $DEBIAN_SUITE_TO_BUILD
     rebuild_all_bpo $DEBIAN_SUITE_TO_BUILD
 done
